var MODULESETS = {}; var ROW_KEYS = {}; var ROW_KEY_SIGNATURES = {};
MODULESETS['background_script.js'] = 'background'; ROW_KEYS['background'] = 'classroom-live.background.en_US.E8cFqPLEeFs.OL';
MODULESETS['inject_script.js'] = 'inject'; ROW_KEYS['inject'] = 'classroom-live.inject.en_US.KsfoC4Y9be8.OL';
MODULESETS['options_script.js'] = 'options'; ROW_KEYS['options'] = 'classroom-live.options.en_US.tNAL3S8vhr4.OL';
MODULESETS['popup_script.js'] = 'popup'; ROW_KEYS['popup'] = 'classroom-live.popup.en_US.6FtCE0dNeUY.OL';
try{
/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var k,_DumpException=function(a){throw a;},aa="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},ba;if("function"==typeof Object.setPrototypeOf)ba=Object.setPrototypeOf;else{var ca;a:{var da={ga:!0},ea={};try{ea.__proto__=da;ca=ea.ga;break a}catch(a){}ca=!1}ba=ca?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var fa=ba,m=function(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(fa)fa(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.O=b.prototype},ha="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},ia=function(a){a=["object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&
global,a];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},ja=ia(this),ka=function(a,b){if(b){var c=ja;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ha(c,a,{configurable:!0,writable:!0,value:b})}};
ka("String.prototype.repeat",function(a){return a?a:function(b){if(null==this)throw new TypeError("The 'this' value for String.prototype.repeat must not be null or undefined");var c=this;if(0>b||1342177279<b)throw new RangeError("Invalid count value");b|=0;for(var d="";b;)if(b&1&&(d+=c),b>>>=1)c+=c;return d}});
var n=this||self,la=function(){},ma=function(a){a.N=void 0;a.H=function(){return a.N?a.N:a.N=new a}},na=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=
typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==b&&"undefined"==typeof a.call)return"object";return b},oa=function(a){var b=na(a);return"array"==b||"object"==b&&"number"==typeof a.length},p=function(a){return"function"==na(a)},q=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b},pa="closure_uid_"+(1E9*Math.random()>>>0),qa=0,ra=function(a,b,c){return a.call.apply(a.bind,arguments)},
sa=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}},r=function(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?r=ra:r=sa;return r.apply(null,arguments)},ta=Date.now||function(){return+new Date},t=function(a,b){function c(){}c.prototype=
b.prototype;a.O=b.prototype;a.prototype=new c;a.prototype.constructor=a};
var u=n.JSON.stringify;
var v=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,v);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};t(v,Error);v.prototype.name="CustomError";
var ua=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},w=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e="string"===typeof a?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},va=Array.prototype.every?function(a,b){return Array.prototype.every.call(a,
b,void 0)}:function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)if(e in d&&!b.call(void 0,d[e],e,a))return!1;return!0},ya=function(a){var b=wa;a=xa(b,a,void 0);return 0>a?null:"string"===typeof b?b.charAt(a):b[a]},xa=function(a,b,c){for(var d=a.length,e="string"===typeof a?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return f;return-1},za=function(a,b){0<=ua(a,b)||a.push(b)},Aa=function(a,b){b=ua(a,b);var c;(c=0<=b)&&Array.prototype.splice.call(a,b,1);return c},
Ba=function(a){return Array.prototype.concat.apply([],arguments)},Ca=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]},Ea=function(a,b,c,d){Array.prototype.splice.apply(a,Da(arguments,1))},Da=function(a,b,c){return 2>=arguments.length?Array.prototype.slice.call(a,b):Array.prototype.slice.call(a,b,c)};
var Fa=/&/g,Ga=/</g,Ha=/>/g,Ia=/"/g,Ja=/'/g,Ka=/\x00/g,La=/[\x00&<>"']/;
var x;a:{var Ma=n.navigator;if(Ma){var Na=Ma.userAgent;if(Na){x=Na;break a}}x=""}var y=function(a){return-1!=x.indexOf(a)};
var Oa=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)},Pa=function(a){var b=0,c;for(c in a)b++;return b},Qa=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b},Ra=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b},Sa=function(a,b){return null!==a&&b in a},Ta="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "),Ua=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Ta.length;f++)c=
Ta[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};
var z=function(a,b){this.a=a===Va&&b||"";this.b=Wa};z.prototype.M=!0;z.prototype.K=function(){return this.a};var Wa={},Va={},Xa=new z(Va,"");
var $a=function(a,b){this.a=a===Ya&&b||"";this.b=Za};$a.prototype.M=!0;$a.prototype.K=function(){return this.a.toString()};var Za={},Ya={};
var bb=function(){this.a="";this.b=ab};bb.prototype.M=!0;bb.prototype.K=function(){return this.a.toString()};var db=function(){var a=cb;if(a instanceof bb&&a.constructor===bb&&a.b===ab)return a.a;na(a);return"type_error:SafeHtml"},ab={},eb=function(a){var b=new bb;b.a=a;return b};eb("<!DOCTYPE html>");var cb=eb("");eb("<br>");
var fb=function(a){var b=new $a(Ya,Xa instanceof z&&Xa.constructor===z&&Xa.b===Wa?Xa.a:"type_error:Const");b instanceof $a&&b.constructor===$a&&b.b===Za?b=b.a:(na(b),b="type_error:TrustedResourceUrl");a.src=b.toString()};
var gb=function(a){La.test(a)&&(-1!=a.indexOf("&")&&(a=a.replace(Fa,"&amp;")),-1!=a.indexOf("<")&&(a=a.replace(Ga,"&lt;")),-1!=a.indexOf(">")&&(a=a.replace(Ha,"&gt;")),-1!=a.indexOf('"')&&(a=a.replace(Ia,"&quot;")),-1!=a.indexOf("'")&&(a=a.replace(Ja,"&#39;")),-1!=a.indexOf("\x00")&&(a=a.replace(Ka,"&#0;")));return a},hb=String.prototype.repeat?function(a,b){return a.repeat(b)}:function(a,b){return Array(b+1).join(a)};
var ib=y("Opera"),jb=y("Trident")||y("MSIE"),kb=y("Edge"),lb=y("Gecko")&&!(-1!=x.toLowerCase().indexOf("webkit")&&!y("Edge"))&&!(y("Trident")||y("MSIE"))&&!y("Edge"),mb=-1!=x.toLowerCase().indexOf("webkit")&&!y("Edge"),nb=function(){var a=n.document;return a?a.documentMode:void 0},ob;
a:{var pb="",qb=function(){var a=x;if(lb)return/rv:([^\);]+)(\)|;)/.exec(a);if(kb)return/Edge\/([\d\.]+)/.exec(a);if(jb)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(mb)return/WebKit\/(\S+)/.exec(a);if(ib)return/(?:Version)[ \/]?(\S+)/.exec(a)}();qb&&(pb=qb?qb[1]:"");if(jb){var rb=nb();if(null!=rb&&rb>parseFloat(pb)){ob=String(rb);break a}}ob=pb}var sb=ob,tb;if(n.document&&jb){var ub=nb();tb=ub?ub:parseInt(sb,10)||void 0}else tb=void 0;var vb=tb;
var wb=function(a,b,c){this.reset(a,b,c,void 0,void 0)};wb.prototype.g=0;wb.prototype.a=null;var xb=0;wb.prototype.reset=function(a,b,c,d,e){this.g="number"==typeof e?e:xb++;this.j=d||ta();this.b=a;this.h=b;this.c=c;delete this.a};wb.prototype.getMessage=function(){return this.h};
var yb=function(a){this.h=a;this.a=this.g=this.b=this.c=null},A=function(a,b){this.name=a;this.value=b};A.prototype.toString=function(){return this.name};var zb=new A("WARNING",900),Ab=new A("INFO",800),Bb=new A("CONFIG",700),Cb=new A("FINE",500),wa=[new A("OFF",Infinity),new A("SHOUT",1200),new A("SEVERE",1E3),zb,Ab,Bb,Cb,new A("FINER",400),new A("FINEST",300),new A("ALL",0)],Db=function(a,b){a.a||(a.a=[]);a.a.push(b)};yb.prototype.getChildren=function(){this.g||(this.g={});return this.g};
var Eb=function(a,b){a.b=b},Fb=function(a){return a.b?a.b:a.c?Fb(a.c):null};yb.prototype.log=function(a,b,c){if(a.value>=Fb(this).value)for(p(b)&&(b=b()),a=new wb(a,String(b),this.h),c&&(a.a=c),c=this;c;){var d=c,e=a;if(d.a)for(var f=0;b=d.a[f];f++)b(e);c=c.c}};
var Gb={},Hb=null,Ib=function(){Hb||(Hb=new yb(""),Gb[""]=Hb,Hb.b=Bb)},Jb=function(){Ib();return Hb},C=function(a){Ib();var b;if(!(b=Gb[a])){b=new yb(a);var c=a.lastIndexOf("."),d=a.substr(c+1);c=C(a.substr(0,c));c.getChildren()[d]=b;b.c=c;Gb[a]=b}return b};
var D=function(a,b){a&&a.log(zb,b,void 0)},Kb=function(a,b){a&&a.log(Cb,b,void 0)};
var Mb=function(a,b){var c=Array.prototype.slice.call(arguments),d=c.shift();if("undefined"==typeof d)throw Error("[goog.string.format] Template required");return d.replace(/%([0\- \+]*)(\d+)?(\.(\d+))?([%sfdiu])/g,function(e,f,g,h,l,B,zd,Ad){if("%"==B)return"%";var Lb=c.shift();if("undefined"==typeof Lb)throw Error("[goog.string.format] Not enough arguments");arguments[0]=Lb;return E[B].apply(null,arguments)})},E={s:function(a,b,c){return isNaN(c)||""==c||a.length>=Number(c)?a:a=-1<b.indexOf("-",
0)?a+hb(" ",Number(c)-a.length):hb(" ",Number(c)-a.length)+a},f:function(a,b,c,d,e){d=a.toString();isNaN(e)||""==e||(d=parseFloat(a).toFixed(e));var f=0>Number(a)?"-":0<=b.indexOf("+")?"+":0<=b.indexOf(" ")?" ":"";0<=Number(a)&&(d=f+d);if(isNaN(c)||d.length>=Number(c))return d;d=isNaN(e)?Math.abs(Number(a)).toString():Math.abs(Number(a)).toFixed(e);a=Number(c)-d.length-f.length;return d=0<=b.indexOf("-",0)?f+d+hb(" ",a):f+hb(0<=b.indexOf("0",0)?"0":" ",a)+d},d:function(a,b,c,d,e,f,g,h){return E.f(parseInt(a,
10),b,c,d,0,f,g,h)}};E.i=E.d;E.u=E.d;
var F=function(a,b,c,d){v.call(this,a);this.details=b?"string"===typeof b?b:b.message:void 0;this.helpText=c;this.errorType=d;a=n.MODULESETS;Pa(a)&&(a=Mb("chrome-extension://%s/(%s):(\\d+):(\\d+)",chrome.runtime.id,Ra(a).join("|")),this.stack=this.stack.replace(new RegExp(a,"g"),Nb));a=C("edulive.errors.Error");Kb(a,this.toString())};t(F,v);F.prototype.toJSON=function(){var a={};Object.getOwnPropertyNames(this).forEach(function(b){a[b]=this[b]},this);return a};F.prototype.name="edulive.errors.Error";
var Nb=function(a,b,c,d){var e=n.MODULESETS;b=e[b];if(!b)return a;a=n.ROW_KEYS[b];var f=n.ROW_KEY_SIGNATURES[b];c-=Pa(e)+1;return f?Mb("https://www.gstatic.com/classroom-live/_/js/k=%s/m=%s/rt=j/d=1/rs=%s:%d:%d",a,b,f,c,d):Mb("https://www.gstatic.com/classroom-live/_/js/k=%s/m=%s/rt=j/d=1:%d:%d",a,b,c,d)},Pb=function(a){F.call(this,"");w(Qa(Ob),function(b){b in a&&(this[b]=a[b])},this)};t(Pb,F);Pb.prototype.name="edulive.errors.SerializedError";
var Ob={ia:"columnNumber",ja:"details",ka:"errorType",la:"fileName",ma:"helpText",na:"lineNumber",oa:"message",pa:"name",qa:"stack",ra:"status",sa:"type"};
var Qb=function(a){if(a.w&&"function"==typeof a.w)return a.w();if("string"===typeof a)return a.split("");if(oa(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Qa(a)};
C("apps.photos.imagurl.ImageUrlOptionsParser");
C("apps.photos.imagurl.ImageUrlOptionsBuilderBase");
var G=function(a,b){this.b={};this.a=[];this.c=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a)if(a instanceof G)for(c=a.F(),d=0;d<c.length;d++)this.set(c[d],a.get(c[d]));else for(d in a)this.set(d,a[d])};G.prototype.w=function(){Rb(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};G.prototype.F=function(){Rb(this);return this.a.concat()};
G.prototype.clear=function(){this.b={};this.c=this.a.length=0};G.prototype.remove=function(a){return H(this.b,a)?(delete this.b[a],this.c--,this.a.length>2*this.c&&Rb(this),!0):!1};var Rb=function(a){if(a.c!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];H(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.c!=a.a.length){var e={};for(c=b=0;b<a.a.length;)d=a.a[b],H(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}};G.prototype.get=function(a,b){return H(this.b,a)?this.b[a]:b};
G.prototype.set=function(a,b){H(this.b,a)||(this.c++,this.a.push(a));this.b[a]=b};G.prototype.forEach=function(a,b){for(var c=this.F(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};var H=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
var Sb=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/\\#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/,Tb=function(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(0<=d){var f=a[c].substring(0,d);e=a[c].substring(d+1)}else f=a[c];b(f,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}};
var I=function(a,b){this.b=this.l=this.c="";this.o=null;this.g=this.a="";this.h=!1;var c;a instanceof I?(this.h=void 0!==b?b:a.h,Ub(this,a.c),this.l=a.l,this.b=a.b,Vb(this,a.o),this.a=a.a,Wb(this,Xb(a.j)),this.g=a.g):a&&(c=String(a).match(Sb))?(this.h=!!b,Ub(this,c[1]||"",!0),this.l=Yb(c[2]||""),this.b=Yb(c[3]||"",!0),Vb(this,c[4]),this.a=Yb(c[5]||"",!0),Wb(this,c[6]||"",!0),this.g=Yb(c[7]||"")):(this.h=!!b,this.j=new J(null,this.h))};
I.prototype.toString=function(){var a=[],b=this.c;b&&a.push(Zb(b,$b,!0),":");var c=this.b;if(c||"file"==b)a.push("//"),(b=this.l)&&a.push(Zb(b,$b,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.o,null!=c&&a.push(":",String(c));if(c=this.a)this.b&&"/"!=c.charAt(0)&&a.push("/"),a.push(Zb(c,"/"==c.charAt(0)?ac:bc,!0));(c=this.j.toString())&&a.push("?",c);(c=this.g)&&a.push("#",Zb(c,cc));return a.join("")};
var Ub=function(a,b,c){a.c=c?Yb(b,!0):b;a.c&&(a.c=a.c.replace(/:$/,""))},Vb=function(a,b){if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.o=b}else a.o=null},Wb=function(a,b,c){b instanceof J?(a.j=b,dc(a.j,a.h)):(c||(b=Zb(b,ec)),a.j=new J(b,a.h))},fc=function(a){return a instanceof I?new I(a):new I(a,void 0)},gc=function(){var a=K;if(".."==a||"."==a)return"";if(-1!=a.indexOf("./")||-1!=a.indexOf("/.")){var b=0==a.lastIndexOf("/",0);a=a.split("/");for(var c=[],d=0;d<a.length;){var e=
a[d++];"."==e?b&&d==a.length&&c.push(""):".."==e?((1<c.length||1==c.length&&""!=c[0])&&c.pop(),b&&d==a.length&&c.push("")):(c.push(e),b=!0)}return c.join("/")}return a},Yb=function(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""},Zb=function(a,b,c){return"string"===typeof a?(a=encodeURI(a).replace(b,hc),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null},hc=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},$b=/[#\/\?@]/g,bc=/[#\?:]/g,
ac=/[#\?]/g,ec=/[#\?@]/g,cc=/#/g,J=function(a,b){this.b=this.a=null;this.c=a||null;this.g=!!b},L=function(a){a.a||(a.a=new G,a.b=0,a.c&&Tb(a.c,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))};J.prototype.add=function(a,b){L(this);this.c=null;a=M(this,a);var c=this.a.get(a);c||this.a.set(a,c=[]);c.push(b);this.b+=1;return this};J.prototype.remove=function(a){L(this);a=M(this,a);return H(this.a.b,a)?(this.c=null,this.b-=this.a.get(a).length,this.a.remove(a)):!1};
J.prototype.clear=function(){this.a=this.c=null;this.b=0};var ic=function(a,b){L(a);b=M(a,b);return H(a.a.b,b)};k=J.prototype;k.forEach=function(a,b){L(this);this.a.forEach(function(c,d){w(c,function(e){a.call(b,e,d,this)},this)},this)};k.F=function(){L(this);for(var a=this.a.w(),b=this.a.F(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};
k.w=function(a){L(this);var b=[];if("string"===typeof a)ic(this,a)&&(b=Ba(b,this.a.get(M(this,a))));else{a=this.a.w();for(var c=0;c<a.length;c++)b=Ba(b,a[c])}return b};k.set=function(a,b){L(this);this.c=null;a=M(this,a);ic(this,a)&&(this.b-=this.a.get(a).length);this.a.set(a,[b]);this.b+=1;return this};k.get=function(a,b){if(!a)return b;a=this.w(a);return 0<a.length?String(a[0]):b};
k.toString=function(){if(this.c)return this.c;if(!this.a)return"";for(var a=[],b=this.a.F(),c=0;c<b.length;c++){var d=b[c],e=encodeURIComponent(String(d));d=this.w(d);for(var f=0;f<d.length;f++){var g=e;""!==d[f]&&(g+="="+encodeURIComponent(String(d[f])));a.push(g)}}return this.c=a.join("&")};
var Xb=function(a){var b=new J;b.c=a.c;a.a&&(b.a=new G(a.a),b.b=a.b);return b},M=function(a,b){b=String(b);a.g&&(b=b.toLowerCase());return b},dc=function(a,b){b&&!a.g&&(L(a),a.c=null,a.a.forEach(function(c,d){var e=d.toLowerCase();d!=e&&(this.remove(d),this.remove(e),0<c.length&&(this.c=null,this.a.set(M(this,e),Ca(c)),this.b+=c.length))},a));a.g=b};
var jc=fc("https://classroomlive-pa.googleapis.com"),N=fc("/v2/"),O=new I(jc),P=!!N.c;P?Ub(O,N.c):P=!!N.l;P?O.l=N.l:P=!!N.b;P?O.b=N.b:P=null!=N.o;var K=N.a;if(P)Vb(O,N.o);else if(P=!!N.a){if("/"!=K.charAt(0))if(jc.b&&!jc.a)K="/"+K;else{var kc=O.a.lastIndexOf("/");-1!=kc&&(K=O.a.substr(0,kc+1)+K)}K=gc()}P?O.a=K:P=""!==N.j.toString();P?Wb(O,Xb(N.j)):P=!!N.g;P&&(O.g=N.g);
var Q=chrome.i18n.getMessage("2050089326602918210");chrome.i18n.getMessage("4849976898594713883",[Q,"https://classroomlive-pa.googleapis.com"]);chrome.i18n.getMessage("9217362152767454370",[Q]);chrome.i18n.getMessage("7604563725603697690");chrome.i18n.getMessage("533692309512814645");chrome.i18n.getMessage("7826444313570725162");chrome.i18n.getMessage("5936353814217802658");chrome.i18n.getMessage("1258929983314547244");chrome.i18n.getMessage("4491595920888170943");chrome.i18n.getMessage("8657495129257769609");
chrome.i18n.getMessage("9200475522066047621");chrome.i18n.getMessage("6042567254866620046",[Q]);chrome.i18n.getMessage("7798244153502527716",[Q]);chrome.i18n.getMessage("4811423455816775324",[Q]);chrome.i18n.getMessage("3727581148109420602");chrome.i18n.getMessage("826991190228103925");chrome.i18n.getMessage("4748990655911819545");var lc=chrome.i18n.getMessage("7582805180132294390",[Q]);chrome.i18n.getMessage("6576961868476783976",[Q]);
var mc=function(a){return u({t:a.j,ln:a.b.name,lv:a.b.value,m:a.getMessage(),n:a.c,s:a.g,e:a.a&&a.a.message})};
var R=function(){this.c=this.c;this.h=this.h};R.prototype.c=!1;R.prototype.v=function(){if(this.h)for(;this.h.length;)this.h.shift()()};
var nc=function(){this.a=new G},oc=function(a){var b=typeof a;return"object"==b&&a||"function"==b?"o"+(Object.prototype.hasOwnProperty.call(a,pa)&&a[pa]||(a[pa]=++qa)):b.charAt(0)+a};k=nc.prototype;k.add=function(a){this.a.set(oc(a),a)};k.removeAll=function(a){a=Qb(a);for(var b=a.length,c=0;c<b;c++)this.remove(a[c])};k.remove=function(a){return this.a.remove(oc(a))};k.clear=function(){this.a.clear()};k.contains=function(a){a=oc(a);return H(this.a.b,a)};k.w=function(){return this.a.w()};
var S=function(a){R.call(this);this.g=(a||5242880)/2;this.o=!1;this.b=[];this.a=0;this.j=r(this.A,this);this.l=new nc};m(S,R);S.prototype.v=function(){pc(this,!1);R.prototype.v.call(this)};var pc=function(a,b){if(b!=a.o){var c=Jb();if(b)Db(c,a.j);else{(c=c.a)&&Aa(c,a.j);c=a.b;if(!Array.isArray(c))for(var d=c.length-1;0<=d;d--)delete c[d];c.length=0;a.a=0}a.o=b}};
S.prototype.A=function(a){if(!this.l.contains(a.c)&&a){a=mc(a);var b=a.length;if(!(b>this.g)){var c=b-(this.g-this.a);if(b+this.a>this.g){var d=0,e=xa(this.b,function(f){d+=f.length;return d>=c},this);Ea(this.b,0,e+1);this.a-=d}za(this.b,a);this.a+=b}}};ma(S);
var qc=!jb||9<=Number(vb);
var rc=function(a){var b=document;return"string"===typeof a?b.getElementById(a):a},tc=function(a,b){Oa(b,function(c,d){c&&"object"==typeof c&&c.M&&(c=c.K());"style"==d?a.style.cssText=c:"class"==d?a.className=c:"for"==d?a.htmlFor=c:sc.hasOwnProperty(d)?a.setAttribute(sc[d],c):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,c):a[d]=c})},sc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",
nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"},wc=function(a,b,c){var d=arguments,e=document,f=String(d[0]),g=d[1];if(!qc&&g&&(g.name||g.type)){f=["<",f];g.name&&f.push(' name="',gb(g.name),'"');if(g.type){f.push(' type="',gb(g.type),'"');var h={};Ua(h,g);delete h.type;g=h}f.push(">");f=f.join("")}f=uc(e,f);g&&("string"===typeof g?f.className=g:Array.isArray(g)?f.className=g.join(" "):tc(f,g));2<d.length&&vc(e,f,d);return f},vc=function(a,b,
c){function d(g){g&&b.appendChild("string"===typeof g?a.createTextNode(g):g)}for(var e=2;e<c.length;e++){var f=c[e];!oa(f)||q(f)&&0<f.nodeType?d(f):w(xc(f)?Ca(f):f,d)}},uc=function(a,b){b=String(b);"application/xhtml+xml"===a.contentType&&(b=b.toLowerCase());return a.createElement(b)},yc=function(a){a&&a.parentNode&&a.parentNode.removeChild(a)},xc=function(a){if(a&&"number"==typeof a.length){if(q(a))return"function"==typeof a.item||"string"==typeof a.item;if(p(a))return"function"==typeof a.item}return!1};
var zc=function(a,b){var c=a.getAttribute("data-sender"),d=a.getAttribute("data-request"),e=a.getAttribute("data-params");a=a.getAttribute("data-expectResponse");if(!c)return b&&D(b,"Missing data-sender attribute"),null;if(!d)return b&&D(b,"Missing data-request attribute"),null;if(a)a=a==(!0).toString();else return b&&D(b,"Missing data-response attribute"),null;if(e)try{var f=JSON.parse(e)}catch(g){if(g instanceof SyntaxError)return b&&D(b,"Invalid data-params attribute"),null}return{sender:c,request:d,
params:f,expectResponse:a}};
var T=function(a,b,c){F.call(this,a,b,c,"connection")};m(T,F);T.prototype.name="edulive.messaging.Error";
var Ac=function(a,b){this.type=a;this.a=this.target=b;this.defaultPrevented=!1};
var Bc=function(a,b){Ac.call(this,b.request,a);this.message=b};m(Bc,Ac);
var Cc="closure_listenable_"+(1E6*Math.random()|0),Dc=0;
var Ec=function(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.capture=!!d;this.L=e;this.key=++Dc;this.removed=this.J=!1},Fc=function(a){a.removed=!0;a.listener=null;a.proxy=null;a.src=null;a.L=null};
var Gc=function(a){this.src=a;this.a={};this.b=0};Gc.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.b++);var g=Hc(a,b,d,e);-1<g?(b=a[g],c||(b.J=!1)):(b=new Ec(b,this.src,f,!!d,e),b.J=c,a.push(b));return b};Gc.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=Hc(e,b,c,d);return-1<b?(Fc(e[b]),Array.prototype.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};
var Ic=function(a,b){var c=b.type;c in a.a&&Aa(a.a[c],b)&&(Fc(b),0==a.a[c].length&&(delete a.a[c],a.b--))};Gc.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,Fc(d[e]);delete this.a[c];this.b--}return b};var Hc=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.removed&&f.listener==b&&f.capture==!!c&&f.L==d)return e}return-1};
var Jc="closure_lm_"+(1E6*Math.random()|0),Kc={},Lc=0,Mc=function(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++)Mc(a,b[f],c,d,e);else(d=q(d)?!!d.capture:!!d,c=Nc(c),a&&a[Cc])?a.b.remove(String(b),c,d,e):a&&(a=Oc(a))&&(b=a.a[b.toString()],a=-1,b&&(a=Hc(b,c,d,e)),(c=-1<a?b[a]:null)&&"number"!==typeof c&&c&&!c.removed&&((e=c.src)&&e[Cc]?Ic(e.b,c):(b=c.type,d=c.proxy,e.removeEventListener?e.removeEventListener(b,d,c.capture):e.detachEvent?e.detachEvent(b in Kc?Kc[b]:Kc[b]="on"+b,d):e.addListener&&
e.removeListener&&e.removeListener(d),Lc--,(b=Oc(e))?(Ic(b,c),0==b.b&&(b.src=null,e[Jc]=null)):Fc(c))))},Oc=function(a){a=a[Jc];return a instanceof Gc?a:null},Pc="__closure_events_fn_"+(1E9*Math.random()>>>0),Nc=function(a){if(p(a))return a;a[Pc]||(a[Pc]=function(b){return a.handleEvent(b)});return a[Pc]};
var U=function(){R.call(this);this.b=new Gc(this);this.V=this;this.C=null};t(U,R);U.prototype[Cc]=!0;U.prototype.removeEventListener=function(a,b,c,d){Mc(this,a,b,c,d)};U.prototype.v=function(){U.O.v.call(this);this.b&&this.b.removeAll(void 0);this.C=null};U.prototype.listen=function(a,b,c,d){return this.b.add(String(a),b,!1,c,d)};
var Qc=function(a,b,c,d){b=a.b.a[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,f=0;f<b.length;++f){var g=b[f];if(g&&!g.removed&&g.capture==c){var h=g.listener,l=g.L||g.src;g.J&&Ic(a.b,g);e=!1!==h.call(l,d)&&e}}return e&&!d.defaultPrevented};
var Rc=function(a,b){this.c=a;this.g=b;this.b=0;this.a=null};Rc.prototype.get=function(){if(0<this.b){this.b--;var a=this.a;this.a=a.next;a.next=null}else a=this.c();return a};var Sc=function(a,b){a.g(b);100>a.b&&(a.b++,b.next=a.a,a.a=b)};
var Tc=function(a){n.setTimeout(function(){throw a;},0)},Uc,Vc=function(){var a=n.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!y("Presto")&&(a=function(){var e=uc(document,"IFRAME");e.style.display="none";fb(e);document.documentElement.appendChild(e);var f=e.contentWindow;e=f.document;e.open();e.write(db());e.close();var g="callImmediate"+Math.random(),h="file:"==f.location.protocol?"*":f.location.protocol+"//"+f.location.host;e=
r(function(l){if(("*"==h||l.origin==h)&&l.data==g)this.port1.onmessage()},this);f.addEventListener("message",e,!1);this.port1={};this.port2={postMessage:function(){f.postMessage(g,h)}}});if("undefined"!==typeof a&&!y("Trident")&&!y("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(void 0!==c.next){c=c.next;var e=c.U;c.U=null;e()}};return function(e){d.next={U:e};d=d.next;b.port2.postMessage(0)}}return function(e){n.setTimeout(e,0)}};
var Wc=function(){this.b=this.a=null},Yc=new Rc(function(){return new Xc},function(a){a.reset()});Wc.prototype.add=function(a,b){var c=Yc.get();c.set(a,b);this.b?this.b.next=c:this.a=c;this.b=c};Wc.prototype.remove=function(){var a=null;this.a&&(a=this.a,this.a=this.a.next,this.a||(this.b=null),a.next=null);return a};var Xc=function(){this.next=this.b=this.a=null};Xc.prototype.set=function(a,b){this.a=a;this.b=b;this.next=null};Xc.prototype.reset=function(){this.next=this.b=this.a=null};
var cd=function(a,b){Zc||$c();ad||(Zc(),ad=!0);bd.add(a,b)},Zc,$c=function(){if(n.Promise&&n.Promise.resolve){var a=n.Promise.resolve(void 0);Zc=function(){a.then(dd)}}else Zc=function(){var b=dd;!p(n.setImmediate)||n.Window&&n.Window.prototype&&!y("Edge")&&n.Window.prototype.setImmediate==n.setImmediate?(Uc||(Uc=Vc()),Uc(b)):n.setImmediate(b)}},ad=!1,bd=new Wc,dd=function(){for(var a;a=bd.remove();){try{a.a.call(a.b)}catch(b){Tc(b)}Sc(Yc,a)}ad=!1};
var W=function(a,b){this.a=0;this.l=void 0;this.g=this.b=this.c=null;this.h=this.j=!1;this.o=[];ed(this,Error("created"));this.A=0;if(a!=la)try{var c=this;a.call(b,function(d){V(c,2,d)},function(d){V(c,3,d)})}catch(d){V(this,3,d)}},fd=function(){this.next=this.g=this.b=this.h=this.a=null;this.c=!1};fd.prototype.reset=function(){this.g=this.b=this.h=this.a=null;this.c=!1};var gd=new Rc(function(){return new fd},function(a){a.reset()}),hd=function(a,b,c){var d=gd.get();d.h=a;d.b=b;d.g=c;return d};
W.prototype.then=function(a,b,c){ed(this,Error("then"));return id(this,p(a)?a:null,p(b)?b:null,c)};W.prototype.$goog_Thenable=!0;W.prototype.cancel=function(a){if(0==this.a){var b=new jd(a);cd(function(){kd(this,b)},this)}};
var kd=function(a,b){if(0==a.a)if(a.c){var c=a.c;if(c.b){for(var d=0,e=null,f=null,g=c.b;g&&(g.c||(d++,g.a==a&&(e=g),!(e&&1<d)));g=g.next)e||(f=g);e&&(0==c.a&&1==d?kd(c,b):(f?(d=f,d.next==c.g&&(c.g=d),d.next=d.next.next):ld(c),md(c,e,3,b)))}a.c=null}else V(a,3,b)},od=function(a,b){a.b||2!=a.a&&3!=a.a||nd(a);a.g?a.g.next=b:a.b=b;a.g=b},id=function(a,b,c,d){var e=hd(null,null,null);e.a=new W(function(f,g){e.h=b?function(h){try{var l=b.call(d,h);f(l)}catch(B){g(B)}}:f;e.b=c?function(h){try{var l=c.call(d,
h);void 0===l&&h instanceof jd?g(h):f(l)}catch(B){g(B)}}:g});e.a.c=a;od(a,e);return e.a};W.prototype.C=function(a){this.a=0;V(this,2,a)};W.prototype.D=function(a){this.a=0;V(this,3,a)};
var V=function(a,b,c){if(0==a.a){a===c&&(b=3,c=new TypeError("Promise cannot resolve to itself"));a.a=1;a:{var d=c,e=a.C,f=a.D;if(d instanceof W){ed(d,Error("then"));od(d,hd(e||la,f||null,a));var g=!0}else{if(d)try{var h=!!d.$goog_Thenable}catch(B){h=!1}else h=!1;if(h)d.then(e,f,a),g=!0;else{if(q(d))try{var l=d.then;if(p(l)){pd(d,l,e,f,a);g=!0;break a}}catch(B){f.call(a,B);g=!0;break a}g=!1}}}g||(a.l=c,a.a=b,a.c=null,nd(a),3!=b||c instanceof jd||qd(a,c))}},pd=function(a,b,c,d,e){var f=!1,g=function(l){f||
(f=!0,c.call(e,l))},h=function(l){f||(f=!0,d.call(e,l))};try{b.call(a,g,h)}catch(l){h(l)}},nd=function(a){a.j||(a.j=!0,cd(a.B,a))},ld=function(a){var b=null;a.b&&(b=a.b,a.b=b.next,b.next=null);a.b||(a.g=null);return b};W.prototype.B=function(){for(var a;a=ld(this);)this.A++,md(this,a,this.a,this.l);this.j=!1};
var md=function(a,b,c,d){if(3==c&&b.b&&!b.c)for(;a&&a.h;a=a.c)a.h=!1;if(b.a)b.a.c=null,rd(b,c,d);else try{b.c?b.h.call(b.g):rd(b,c,d)}catch(e){sd.call(null,e)}Sc(gd,b)},rd=function(a,b,c){2==b?a.h.call(a.g,c):a.b&&a.b.call(a.g,c)},ed=function(a,b){if("string"===typeof b.stack){var c=b.stack.split("\n",4)[3];b=b.message;b+=Array(11-b.length).join(" ");a.o.push(b+c)}},qd=function(a,b){a.h=!0;cd(function(){if(a.h){if(b&&"string"===typeof b.stack&&a.o.length){for(var c=["Promise trace:"],d=a;d;d=d.c){for(var e=
a.A;0<=e;e--)c.push(d.o[e]);c.push("Value: ["+(3==d.a?"REJECTED":"FULFILLED")+"] <"+String(d.l)+">")}b.stack+="\n\n"+c.join("\n")}sd.call(null,b)}})},sd=Tc,jd=function(a){v.call(this,a)};t(jd,v);jd.prototype.name="cancel";
var td=function(a,b,c){R.call(this);this.a=a;this.j=b||0;this.b=c;this.g=r(this.ha,this)};t(td,R);k=td.prototype;k.G=0;k.v=function(){td.O.v.call(this);this.stop();delete this.a;delete this.b};k.start=function(a){this.stop();var b=this.g;a=void 0!==a?a:this.j;if(!p(b))if(b&&"function"==typeof b.handleEvent)b=r(b.handleEvent,b);else throw Error("Invalid listener argument");this.G=2147483647<Number(a)?-1:n.setTimeout(b,a||0)};k.stop=function(){0!=this.G&&n.clearTimeout(this.G);this.G=0};
k.ha=function(){this.G=0;this.a&&this.a.call(this.b)};
var X=function(a,b){U.call(this);this.a=a;this.id=b||window.location.pathname;this.Z=!("undefined"==typeof window.chrome||!chrome||!chrome.runtime)};m(X,U);X.prototype.sendRequest=function(a,b,c){return new W(function(d,e){var f={sender:this.id,request:a,params:b,expectResponse:!0};var g=c||4E4;g=new td(r(this.fa,this,d,e,f),g);d=r(this.ea,this,d,e,f,g);Kb(this.a,this.id+": Sending (and expect response):"+u(f));this.sendMessage(f,d);g.start()},this)};
X.prototype.sendMessage=function(a,b){if(!this.Z)throw new T("Not running in Chrome.",navigator.appVersion);chrome.runtime.sendMessage(a,b)};
X.prototype.ea=function(a,b,c,d,e){var f=chrome.runtime.lastError;d.c||(d.c=!0,d.v());f?(D(this.a,this.id+": Failed sending "+c.request+". Reason: "+f.message),b(new T("Failed to dispatch message. There was no recipient to receive the message.",f))):!q(e)||void 0===e.response&&void 0===e.error?b(new T("Invalid response from message request.",u(e))):(d=this.a,c=this.id+": Received response: "+u(e)+" for message: "+u(c),d&&d.log(e.error?zb:Cb,c,void 0),void 0!==e.response?a(e.response):b(new Pb(e.error)))};
X.prototype.fa=function(a,b,c){D(this.a,this.id+": Failed to receive a response to "+c.request+" in the time alotted.");b(new T("Failed to receive a response in the time alotted.",c.request,lc))};
var ud=function(a){var b=["sender","request","expectResponse"];if(!q(a))return!1;q(b)&&(b=Qa(b));return va(b,function(c){return Sa(a,c)})};
var Y=function(a,b){b=b||C("edulive.messaging.InternalMessageDispatcher");X.call(this,b,a);this.j=r(this.aa,this);chrome.runtime.onMessage.addListener(this.j);chrome.runtime.onMessageExternal&&chrome.runtime.onMessageExternal.addListener(this.j);this.P=r(this.W,this);chrome.runtime.onConnectExternal&&chrome.runtime.onConnectExternal.addListener(this.P);this.I={};this.g={};this.D={}};m(Y,X);
Y.prototype.v=function(){w(Ra(this.g),function(a){vd(this,a,!0)},this);this.I={};chrome.runtime.onConnectExternal&&chrome.runtime.onConnectExternal.removeListener(this.P);chrome.runtime.onMessageExternal&&chrome.runtime.onMessageExternal.removeListener(this.j);chrome.runtime.onMessage.removeListener(this.j);X.prototype.v.call(this)};Y.prototype.sendMessage=function(a,b){b?wd(this,a,b)||X.prototype.sendMessage.call(this,a,b):(cd(r(this.A,this,a)),X.prototype.sendMessage.call(this,a,b),xd(this,a))};
var xd=function(a,b){Oa(a.g,function(c){c.postMessage(b)},a)};Y.prototype.aa=function(a,b,c){if(void 0===a||!q(a))return!1;if(!ud(a))return D(this.a,this.id+": Invalid message: "+u(a)+" from: "+u(b)),!1;if(a.sender==this.id)return!1;Kb(this.a,this.id+": Received message: "+u(a)+" from: "+u(b));if(a.expectResponse)return this.T(b.id,a,c);this.A(a);return!1};
Y.prototype.A=function(a){var b=new Bc(this,a),c;if(a=this.C)for(c=[];a;a=a.C)c.push(a);a=this.V;var d=b.type||b;if("string"===typeof b)b=new Ac(b,a);else if(b instanceof Ac)b.target=b.target||a;else{var e=b;b=new Ac(d,a);Ua(b,e)}e=!0;if(c)for(var f=c.length-1;0<=f;f--){var g=b.a=c[f];e=Qc(g,d,!0,b)&&e}g=b.a=a;e=Qc(g,d,!0,b)&&e;e=Qc(g,d,!1,b)&&e;if(c)for(f=0;f<c.length;f++)g=b.a=c[f],e=Qc(g,d,!1,b)&&e};Y.prototype.T=function(a,b,c){return a==chrome.runtime.id&&b.sender==this.id?!1:wd(this,b,c)};
var wd=function(a,b,c){var d=b.request;if(!Sa(a.I,d))return!1;var e=new Bc(a,b);try{var f=(0,a.I[d])(e);if(f){var g=r(a.da,a,b,c),h=r(a.o,a,b,c);f.then(g,h)}return!!f}catch(l){return a.o(b,c,l),!1}};Y.prototype.da=function(a,b,c){try{JSON.stringify(c),Kb(this.a,"Responding to "+u(a)+" with "+u(c)),b({response:c})}catch(d){this.o(a,b,d)}};
Y.prototype.o=function(a,b,c){if("Attempting to use a disconnected port object"==c.message)D(this.a,a.sender+" disconnected! Cannot respond to "+u(a));else{c instanceof Error&&(c=new Pb(c));try{JSON.stringify(c),D(this.a,"Responding to "+u(a)+" with the error "+u(c)),b({error:Object(c)})}catch(d){D(this.a,"Failed to serialize: "+(p(c.toString)?c.toString():c)+". Returning "+(p(d.toString)?d.toString():d)+" instead."),this.o(a,b,d)}}};
var vd=function(a,b,c){var d=a.a;d&&d.log(Ab,"Ending connection with "+b,void 0);if(d=a.g[b]){var e=a.g;b in e&&delete e[b];c&&d.disconnect();c=a.D[b];a=a.D;b in a&&delete a[b];d.onDisconnect.removeListener(c)}};
Y.prototype.W=function(a){if(a.name!=this.id)Kb(this.a,"Ignoring connection from "+JSON.stringify(a)+" because it is for another page.");else{var b=a.sender;if(b){var c=[];b.id&&c.push(b.id);b.url&&c.push(b.url);c.length?(b=c.join("|"),Sa(this.g,b)?(D(this.a,"Already have a connection with "+b+". Disconnecting"),a.disconnect()):((c=this.a)&&c.log(Ab,"Establishing connection with "+b,void 0),this.g[b]=a,c=r(this.X,this,b),a.onDisconnect.addListener(c),this.D[b]=c)):(D(this.a,"Could not find an id for "+
JSON.stringify(a)+". Disconnecting."),a.disconnect())}}};Y.prototype.X=function(a){vd(this,a)};ma(Y);
var Z=function(a){var b=chrome.runtime.id,c="messaging:"+b,d="requests:"+b,e="events:"+b;Y.call(this,a||c,C("edulive.messaging.InjectedMessageDispatcher"));this.B=yd(c);this.ca=yd(d,this.B);this.Y=yd(e,this.B);this.S=new MutationObserver(r(this.$,this));this.S.observe(this.ca,{childList:!0});this.l={};(a=this.a)&&a.log(Ab,"Installed for "+b,void 0)};m(Z,Y);Z.prototype.v=function(){this.S.disconnect();Oa(this.l,function(a){a.cancel()},this);this.l={};yc(this.B);Y.prototype.v.call(this)};
Z.prototype.A=function(a){var b=this.Y;do var c=["message",a.sender,a.request,ta(),Math.floor(1E6*Math.random())].join(":");while(rc(c));c=wc("DIV",{id:c,style:"display:none"});c.setAttribute("data-sender",a.sender);c.setAttribute("data-request",a.request);c.setAttribute("data-expectResponse",a.expectResponse);void 0!==a.params&&c.setAttribute("data-params",JSON.stringify(a.params));b&&b.appendChild(c)};Z.prototype.T=function(){return!1};
var yd=function(a,b){var c={};b=b||document.body;c.id=a;c.style="display:none";a=wc("DIV",c);b.appendChild(a);return a};
Z.prototype.$=function(a){a&&w(a,function(b){b.addedNodes&&w(Ca(b.addedNodes),function(c){var d=c.getAttribute("id")||"unknown";if((c=zc(c,this.a))&&c.expectResponse){var e=r(this.R,this,d,"data-response"),f=r(this.R,this,d,"data-error");c=this.sendRequest(c.request,c.params).then(e,f);e=r(this.ba,this,d);ed(c,Error("thenAlways"));e=hd(e,e,void 0);e.c=!0;od(c,e);this.l[d]=c}else D(this.a,"Skipping invalid request "+d)},this)},this)};
Z.prototype.R=function(a,b,c){var d=rc(a);d?d.setAttribute(b,JSON.stringify(c)):D(this.a,a+" was removed before the response was received.")};Z.prototype.ba=function(a){var b=this.l;a in b&&delete b[a]};ma(Z);
(function(a,b){S.H();var c=b||ya(function(f){return"INFO"==f.name});a=a||!/^[\s\xa0]*$/.test("")&&[""];b="HangingGetChannel LcsPushChannel invalidation-hr goog.net.BrowserChannel webmonitoring.MemoryUsageReporter wiz.Dispatcher goog.net.NetworkTester BrowserChannelImpl bc-watchdog".split(" ");var d=S.H();null!=c&&Eb(Jb(),c);if(a&&0<a.length){c=function(f){d.A(f)};for(var e=0;e<a.length;++e)Db(C(a[e]),c)}else pc(d,!0);b&&0<b.length&&w(b,function(f){d.l.add(f)})})();Z.H();
document.addEventListener("unload",function(){var a=Z.H();a.c||(a.c=!0,a.v())});

}catch(e){_DumpException(e)}
// Google Inc.
